export const PLAYER_MOVEMENT_HORIZONTAL_VELOCITY = 20;
export const PLAYER_BULLET_MAX_COUNT = 10;

export const BOT_FIGHTER_MOVEMENT_VERTICAL_VELOCITY = 12;

export const BOT_SCOUT_MOVEMENT_VERTICAL_VELOCITY = 10;
export const ENEMY_SCOUT_MOVEMENT_HORIZONTAL_VELOCITY = 9;
export const ENEMY_SCOUT_MOVEMENT_MAX_X = 100;

export const COMPONENT_MOVEMENT_HORIZONTAL_DRAG = 0.01;
export const COMPONENT_MOVEMENT_HORIZONTAL_MAX_VELOCITY = 220;
